name: Build and deploy Node.js app to Azure Web App - plantastik

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Create a ZIP archive of the application
      - name: Create ZIP Archive
        run: |
          zip -r node-app.zip .

      - name: Upload ZIP artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-zip
          path: node-app.zip


      - name: Download ZIP artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-zip

      - name: Extract ZIP Archive
        run: |
          unzip node-app-zip -d extracted
